//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janush.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Janush.Core.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response received. Please ensure that product website is currently reachable and not under maintenance work..
        /// </summary>
        public static string ErrorProductLoadInvalidResponse {
            get {
                return ResourceManager.GetString("ErrorProductLoadInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response received. Please ensure that the given URL is valid and the product website is currently reachable..
        /// </summary>
        public static string ErrorProductLoadNoResponse {
            get {
                return ResourceManager.GetString("ErrorProductLoadNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we were unable to detect a valid product under the given URL..
        /// </summary>
        public static string ErrorProductLoadNotDetected {
            get {
                return ResourceManager.GetString("ErrorProductLoadNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we were unable to detect the product properties..
        /// </summary>
        public static string ErrorProductLoadNotFound {
            get {
                return ResourceManager.GetString("ErrorProductLoadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A redirect was encountered during product load. Please ensure that the product is still there and available..
        /// </summary>
        public static string ErrorProductLoadRedirected {
            get {
                return ResourceManager.GetString("ErrorProductLoadRedirected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we were unable to detect a valid language with provided URL..
        /// </summary>
        public static string ErrorProductLoadUnknownCulture {
            get {
                return ResourceManager.GetString("ErrorProductLoadUnknownCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we were unable to detect a valid product name in the given URL..
        /// </summary>
        public static string ErrorProductLoadUnknownName {
            get {
                return ResourceManager.GetString("ErrorProductLoadUnknownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we were unable to detect a valid product price in the given URL..
        /// </summary>
        public static string ErrorProductLoadUnknownPrice {
            get {
                return ResourceManager.GetString("ErrorProductLoadUnknownPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine current product name..
        /// </summary>
        public static string ErrorProductUpdateName {
            get {
                return ResourceManager.GetString("ErrorProductUpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine current product price. Please ensure that price selector is still valid..
        /// </summary>
        public static string ErrorProductUpdatePriceElementNotFound {
            get {
                return ResourceManager.GetString("ErrorProductUpdatePriceElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the current product price. Please ensure that price selector is still valid..
        /// </summary>
        public static string ErrorProductUpdatePriceRead {
            get {
                return ResourceManager.GetString("ErrorProductUpdatePriceRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name has changed from „{0}” to „{1}”..
        /// </summary>
        public static string NotificationNameChanged {
            get {
                return ResourceManager.GetString("NotificationNameChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neat! Price has decreased from {0} to {1}!.
        /// </summary>
        public static string NotificationPriceDecrease {
            get {
                return ResourceManager.GetString("NotificationPriceDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! Price has increased from {0} to {1}..
        /// </summary>
        public static string NotificationPriceIncrease {
            get {
                return ResourceManager.GetString("NotificationPriceIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while tracking the product. .
        /// </summary>
        public static string NotificationTrackingGenericError {
            get {
                return ResourceManager.GetString("NotificationTrackingGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking is currently active. Your product is being watched periodically..
        /// </summary>
        public static string TrackingStatusActive {
            get {
                return ResourceManager.GetString("TrackingStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is disabled from tracking. To enable it, use product options..
        /// </summary>
        public static string TrackingStatusDisabled {
            get {
                return ResourceManager.GetString("TrackingStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during tracking for this product..
        /// </summary>
        public static string TrackingStatusError {
            get {
                return ResourceManager.GetString("TrackingStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking is about to start shortly....
        /// </summary>
        public static string TrackingStatusIdle {
            get {
                return ResourceManager.GetString("TrackingStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fresh data for this product is currently being pulled..
        /// </summary>
        public static string TrackingStatusUpdating {
            get {
                return ResourceManager.GetString("TrackingStatusUpdating", resourceCulture);
            }
        }
    }
}
