theme: jekyll-theme-minimal
title: Janush
description: Janush helps you track product prices on plenty of e-commerce websites around the world. You get notified on every price change to make sure you buy your product at the lowest price possible with no fake sales.
